### ISSUE TITLE
Initialize a planner with a Catalog

### ISSUE THREAD

**Issue by pietercolpaert** [openplannerteam/planner.js#11]
Each Planner instance should be initialized with a URL to a dcat:Catalog. This catalog should be used for selecting and discovering the right sources.

TODO:
 * [ ] Make sure there’s a good catalog for route planners we can rely on

For now, we could just instantiate each ConnectionsProvider with a URL. Each Planner should be able to have multiple ConnectionsProviders.

**Comment by pietercolpaert** [comment]
The constructor of the Planner should be an array of entrypoints. For every new query, you might decide to turn on/off certain sources.

**Comment by SimonVanneste** [comment]
You can now bind a Catalog with configurations for connection and stop fetchers to the DI container.
The configurations get read by a I(Connections/Stops)Provider and a I(Connections/Fetcher)Fetcher gets constructed per configuration. The provider also serves as the interface for other classes to get connections/stops.
