### ISSUE TITLE
Parsing of coordinates is broken

### ISSUE THREAD

**Issue by xivk** [openplannerteam/planner.js#138]
I'm not 100% sure, not very good in typescript but I think so:

https://github.com/openplannerteam/planner.js/blob/ac550dc94f9c1bea2d580eab6a347a291211d6ac/src/query-runner/LocationResolverConvenience.ts#L30

I doesn't seem to parse this correctly when coordinates are for example in canada:

Error: "Location "geo:52.1483493,-106.7218868" is a string, but not an ID and not a valid stop name"

**Comment by xivk** [comment]
Looks like any coordinate with a '-' sign in it, reproduce this by checking for example in Dublin.

**Comment by pietercolpaert** [comment]
Wasn’t this already fixed @hdelva?

**Comment by hdelva** [comment]
It is, but the bug is still in configuroute because it hasn't been deployed for a while.
