### ISSUE TITLE
Investigate: which classes can be singleton scoped

### ISSUE THREAD

**Issue by SimonVanneste** [openplannerteam/planner.js#16]
Mainly beneficial for performance (probably): data gets loaded only once
Not sure if all classes can be automatically, e.g. those keeping state during processing

**Comment by pietercolpaert** [comment]
Not sure what you mean by this. Do you mean that some functionality should just be available from a namespace?

**Comment by SimonVanneste** [comment]
https://github.com/inversify/InversifyJS/blob/master/wiki/scope.md
Some classes like stops fetchers should/could probably only be instantiated only once (singleton).
They don't have any processing state, so no need for new instances every time they get injected.
But more importantly: stop fetchers load their data once per instance, so only having one instance is beneficial
