### ISSUE TITLE
Support splitting and joining trips by implementing lc:nextConnection

### ISSUE THREAD

**Issue by pietercolpaert** [openplannerteam/planner.js#18]
Cfr. the example in the spec (just updated): https://linkedconnections.org/specification/1-0#splitting-or-joining

lc:nextConnection allows to add additional no-need-to-transfer information, next to the gtfs:trip that can remain the same.

No published dataset does this yet, but it is already supported in gtfs2lc. We are asking SNCB to add this information to their GTFS feeds.

Also relevant for Itinero /cc @pietervdvn

**Comment by SimonVanneste** [comment]
I'm doing the deserialisation part atm (adding lc:nextConnection to IConnection's returned from ConnectionsIterator)
