### ISSUE TITLE
Show less stop markers on codepen example

### ISSUE THREAD

**Issue by SimonVanneste** [openplannerteam/planner.js#58]
Only show biggest stations by filtering on `averageStopTimes`

**Comment by SimonVanneste** [comment]
@pietercolpaert You talked about using `avgStopTimes`, but that doesn't really give a satisfying result in our eyes:
https://codepen.io/maximtmartin/pen/yGMzLM

**Comment by pietercolpaert** [comment]
Result is okay-ish what I’m concerned. The pen can easily be adapted by anyone to use a different property :)
