### ISSUE TITLE
Transfers strategies

### ISSUE THREAD

**Issue by pietercolpaert** [openplannerteam/planner.js#7]
Different strategies may apply:
 * Birds-eye distance calculation every time a stop is discovered
 * Only use parent Station property (not yet implemented in a dataset)
 * Use only the same stop identifiers...

And different route planner strategies may be used across one trip

Make sure this is configurable

**Comment by SimonVanneste** [comment]
Now there's ReachableStopsSearchPhase (Initial, Transfer, Final) and JourneyExtractionPhase (also Initial, Transfer and Final)

**Comment by pietercolpaert** [comment]
Nice!
