### ISSUE TITLE
Implement spatial quad tree for making first selection of reachable stops

### ISSUE THREAD

**Issue by SimonVanneste** [openplannerteam/planner.js#99]
Instead of manual search:
https://github.com/openplannerteam/planner.js/blob/9a90b95b736b4715d020979aa4a341441390d03b/src/planner/stops/ReachableStopsFinderRoadPlanner.ts#L57-L65

**Comment by pietercolpaert** [comment]
This has been changed by @hdelva to using a dataset with delaunay triangulations
